"""fix_match_judge_foreign_keys

Revision ID: 28950c49c36c
Revises: add_judges_and_referees
Create Date: 2025-06-04 22:36:27.376826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28950c49c36c'
down_revision: Union[str, None] = 'add_judges_and_referees'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_referees_id', table_name='referees')
    op.drop_table('referees')
    op.drop_constraint('matches_referee_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_judge_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'judges', ['judge_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'judges', ['referee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_judge_id_fkey', 'matches', 'users', ['judge_id'], ['id'])
    op.create_foreign_key('matches_referee_id_fkey', 'matches', 'users', ['referee_id'], ['id'])
    op.create_table('referees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('competition_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name='referees_competition_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='referees_pkey')
    )
    op.create_index('ix_referees_id', 'referees', ['id'], unique=False)
    # ### end Alembic commands ###
