"""add phone email organization to user

Revision ID: 8081af2b3b85
Revises: 66e988b38e59
Create Date: 2025-05-16 13:06:15.287386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8081af2b3b85'
down_revision: Union[str, None] = '66e988b38e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organization')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
