"""Add participant_type/id fields to matches

Revision ID: 877844802ea3
Revises: 1f3ee0aeea3a
Create Date: 2025-05-20 18:24:13.059812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877844802ea3'
down_revision: Union[str, None] = '1f3ee0aeea3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('red_participant_type', sa.String(length=20), nullable=False))
    op.add_column('matches', sa.Column('red_participant_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('blue_participant_type', sa.String(length=20), nullable=False))
    op.add_column('matches', sa.Column('blue_participant_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('winner_participant_type', sa.String(length=20), nullable=True))
    op.add_column('matches', sa.Column('winner_participant_id', sa.Integer(), nullable=True))
    op.drop_constraint('matches_blue_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_winner_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_red_id_fkey', 'matches', type_='foreignkey')
    op.drop_column('matches', 'winner_id')
    op.drop_column('matches', 'blue_id')
    op.drop_column('matches', 'red_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('red_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('blue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('winner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('matches_red_id_fkey', 'matches', 'users', ['red_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('matches_winner_id_fkey', 'matches', 'users', ['winner_id'], ['id'])
    op.create_foreign_key('matches_blue_id_fkey', 'matches', 'users', ['blue_id'], ['id'], ondelete='SET NULL')
    op.drop_column('matches', 'winner_participant_id')
    op.drop_column('matches', 'winner_participant_type')
    op.drop_column('matches', 'blue_participant_id')
    op.drop_column('matches', 'blue_participant_type')
    op.drop_column('matches', 'red_participant_id')
    op.drop_column('matches', 'red_participant_type')
    # ### end Alembic commands ###
