"""Add team and individual participants

Revision ID: 9f6893b673be
Revises: 8081af2b3b85
Create Date: 2025-05-17 23:07:08.053402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6893b673be'
down_revision: Union[str, None] = '8081af2b3b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='application_participants_application_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='application_participants_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='application_participants_pkey')
    )
    # ### end Alembic commands ###
