"""Add stage and status to Match

Revision ID: b24073f05013
Revises: 0b22d95d4d3d
Create Date: 2025-05-24 13:52:00.688103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24073f05013'
down_revision: Union[str, None] = '0b22d95d4d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('stage', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('matches', 'competition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'competition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'stage')
    # ### end Alembic commands ###
