"""Make red_id and blue_id nullable

Revision ID: d6f1b69089e9
Revises: 1f3ee0aeea3a
Create Date: 2025-05-19 20:34:12.735837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f1b69089e9'
down_revision: Union[str, None] = '1f3ee0aeea3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matches_blue_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_red_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['red_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'matches', 'users', ['blue_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_red_id_fkey', 'matches', 'users', ['red_id'], ['id'])
    op.create_foreign_key('matches_blue_id_fkey', 'matches', 'users', ['blue_id'], ['id'])
    # ### end Alembic commands ###
